### Delayed Rejection

Finally, there is a technique called delayed rejection. Essentially, if proposal $x'$ is rejected, a backup proposal $x''$ is immedeatly proposed, with an acceptance probability that takes into account the rejection of the first proposal to maintain the desired stationary distribution.  This literally increases the likelihood of acceptance and thus the overall efficiency of the sampler. This technique has interesting implications to the interplay between the first and second proposal, specifically selecting a distribution for which cross model proposals are generated frequently as the first proposal, with a proposal that assigns higher weight inside a model as the backup. This allows us to attempt to change state space frequently without being stuck on the same initial state for multiple iterations.



Simulated annealing [@geman1984stochastic] is a method for function optimization. This algorithm can be extended to a trans-dimensional case where an optimal model may need to be determined [@andrieu2000reversible]. In this case, let $f$ be the quantity we want to minimize, maybe with some penalization terms to mimic AIC or BIC. Trans-dimensional simulated annealing proceeds by using reversible jump moves to construct a Markov chain with appropriate invariant distribution. Specifically, at phase $i$ with temperature $T_i$, the target distribution is the Boltzmann distribution with parameter $T_i$, $b_{T_i}(k, \theta_i) \propto \exp(-f(k, \theta_k)/T_i)$. Once equilibrium achieved in the chain, the temperature is decreased and a new phase is started from the state the chain ended in. This process of sampling a reversible Markov chain until reaching equilibrium with the target distribution and the reducing the temperature continues until $T_i = 0$. This process produces a chain that approximates a distribution with all of its mass at the (penalized) minimum of the objective function.